import type { BookSummary, ChapterWorkspaceData, SidebarData } from "./types.js";

export const mockRecentBooks: readonly BookSummary[] = [
  {
    id: "old-city-radio",
    title: "旧城区无线电",
    genre: "末日悬疑",
    currentChapterTitle: "地下车库信号",
    currentChapterNumber: 3,
    protagonistName: "林澈",
    status: "草稿中",
    updatedAt: "今天 18:42",
    logline: "旧城区灾变后，主角通过异常无线电追查避难所广播真假。",
    writtenChapters: 3,
    totalWords: 48600,
    projectPath: "/mock/story-engine-ng/旧城区无线电",
  },
  {
    id: "fog-town-letters",
    title: "雾镇来信",
    genre: "民俗悬疑",
    currentChapterTitle: "纸灯下的回信",
    currentChapterNumber: 8,
    protagonistName: "沈砚",
    status: "待确认",
    updatedAt: "昨天 23:10",
    logline: "雾镇旧邮局重新投递亡者来信，主角沿着信件追查失踪亲人的下落。",
    writtenChapters: 8,
    totalWords: 126400,
    projectPath: "/mock/story-engine-ng/雾镇来信",
  },
  {
    id: "star-port-sleeper",
    title: "星港沉睡者",
    genre: "科幻冒险",
    currentChapterTitle: "冷冻舱的第七次唤醒",
    currentChapterNumber: 12,
    protagonistName: "陆祈",
    status: "可继续下一章",
    updatedAt: "5月15日 09:28",
    logline: "废弃星港深处的冷冻舱不断重启，主角必须判断醒来的自己是否仍是原本的人。",
    writtenChapters: 12,
    totalWords: 214000,
    projectPath: "/mock/story-engine-ng/星港沉睡者",
  },
];

export const mockWorkspaceData: ChapterWorkspaceData = {
  projectName: "旧城区无线电",
  currentChapter: { id: "ch-003", chapterNumber: 3, title: "地下车库信号", status: "current" },
  chapters: [
    { id: "ch-001", chapterNumber: 1, title: "午夜频率", status: "committed" },
    { id: "ch-002", chapterNumber: 2, title: "废弃避难所", status: "committed" },
    { id: "ch-003", chapterNumber: 3, title: "地下车库信号", status: "current" },
    { id: "ch-004", chapterNumber: 4, title: "地下二层的回响", status: "draft" },
    { id: "ch-005", chapterNumber: 5, title: "失真的广播坐标", status: "planned" },
    { id: "ch-006", chapterNumber: 6, title: "消防通道里的脚印", status: "planned" },
    { id: "ch-007", chapterNumber: 7, title: "避难所门后的名单", status: "planned" },
    { id: "ch-008", chapterNumber: 8, title: "旧铜哨的回声", status: "planned" },
  ],
  flowStatus: "idle",
  draft: {
    chapterNumber: 3,
    title: "地下车库信号",
    status: "draft",
    wordCount: 1870,
    content:
      "林澈把收音机贴在耳边，调到 87.5MHz。噪声中，那个声音又出现了，像有人在很远的地方对着麦克风喘息。\n\n[……第三区……地下二层……不要相信广播里的坐标……]\n\n声音断了。林澈看了一眼避难所墙上的地图，第三区就在公寓楼正下方，那个已经废弃了三年的地下车库。\n\n他把收音机塞进背包，确认了一下物资：半瓶水、手电筒、一把备用钥匙，还有那个从上一章带出来的旧铜哨。\n\n走廊里弥漫着潮湿和铁锈的味道。应急灯的绿光每隔几秒就闪烁一次，把他的影子拉得很长，又压缩得很短。\n\n他需要确认信号源。但他也知道，自己昨晚一夜没睡，身体已经疲惫到了极限。",
    savedContent:
      "林澈把收音机贴在耳边，调到 87.5MHz。噪声中，那个声音又出现了，像有人在很远的地方对着麦克风喘息。\n\n[……第三区……地下二层……不要相信广播里的坐标……]\n\n声音断了。林澈看了一眼避难所墙上的地图，第三区就在公寓楼正下方，那个已经废弃了三年的地下车库。\n\n他把收音机塞进背包，确认了一下物资：半瓶水、手电筒、一把备用钥匙，还有那个从上一章带出来的旧铜哨。\n\n走廊里弥漫着潮湿和铁锈的味道。应急灯的绿光每隔几秒就闪烁一次，把他的影子拉得很长，又压缩得很短。\n\n他需要确认信号源。但他也知道，自己昨晚一夜没睡，身体已经疲惫到了极限。",
  },
  messages: [
    {
      id: "msg-001",
      role: "user",
      content: "我想让主角去地下车库确认无线电信号源，但不要立刻揭开真相。",
      createdAt: "02:15",
    },
    {
      id: "msg-002",
      role: "assistant",
      content:
        "可以。当前主角昨晚通宵，状态疲惫；他知道无线电信号异常，但不知道广播坐标真假。建议本章推进信号源，穿插地下车库异响伏笔，结尾保留危险感。",
      createdAt: "02:16",
    },
  ],
  protagonist: {
    name: "林澈",
    age: "尚未配置",
    identity: "旧城区幸存者",
    currentGoal: "确认无线电信号源",
    physicalState: ["昨晚通宵", "疲惫", "轻微脱水"],
    mentalState: ["警惕", "怀疑", "紧张"],
    resourceState: ["半瓶水", "无稳定补给"],
    currentSituation: "正准备前往地下车库确认信号源",
    boundaries: ["不要提前揭开广播真相", "不要让主角知道不该知道的信息", "不要写成任务清单"],
    cannotDo: ["不能提前知道广播真相"],
    speechStyle: "克制，少解释",
    speechSamples: ["先确认声音从哪来。"],
  },
  location: {
    currentLocation: "旧城区公寓楼，准备前往地下车库",
    currentPosition: "12层避难所",
    previousLocation: "12层避难所",
    transitionStatus: "moving",
    floors: ["12层", "地下二层"],
    rooms: ["避难所", "消防通道", "配电室"],
    entrances: ["楼梯间"],
    exits: ["消防通道"],
    resources: ["应急灯", "配电箱"],
    fixedFacts: ["地下车库已废弃三年"],
    risks: ["未知区域", "黑暗中存在未知威胁"],
    nearbyLocations: ["地下二层停车场", "消防通道", "配电室"],
    travelRules: ["12层到地下二层需要走消防通道"],
  },
  time: {
    currentStoryDay: "第 3 天",
    currentTimeOfDay: "深夜",
    latestChapter: "第 3 章",
    latestEvent: "主角准备前往地下车库确认信号源",
  },
  knowledge: {
    knownFacts: ["无线电信号异常", "避难所广播可能有问题"],
    unknownTruths: ["广播背后的真实来源", "避难所真实目的"],
    forbiddenReveals: ["广播真相", "避难所真实目的"],
  },
  assets: {
    carriedItems: ["旧收音机", "手电筒", "半瓶水", "备用钥匙"],
    availableAssets: ["手电筒", "备用钥匙"],
    unavailableAssets: ["无稳定补给"],
    resources: ["无稳定补给"],
    properties: ["12层公寓避难所"],
    containers: [{ name: "双肩背包", contents: ["旧收音机", "半瓶水", "备用钥匙"] }],
    plotCriticalItems: ["旧收音机", "备用钥匙"],
    assetRules: ["旧收音机不能凭空变成通信设备"],
  },
  memory: {
    activeForeshadowing: ["无线电异常信号", "地下车库异响"],
    openThreads: ["避难所广播真假"],
    arcGoals: ["在旧城区灾变中生存下来"],
    recentTimeline: ["第1章：发现神秘频率", "第2章：在避难所发现旧铜哨", "第3章：准备进入地下车库"],
  },
  risks: [
    { id: "risk-001", level: "high", text: "不要提前揭开广播真相" },
    { id: "risk-002", level: "high", text: "不要让主角知道不该知道的信息" },
    { id: "risk-003", level: "medium", text: "不要写成任务清单" },
  ],
  hardConstraints: ["不要提前揭开隐藏真相", "不要凭空增加关键资产", "不要改变已登记地点结构"],
  foundationCompleteness: {
    passed: true,
    readinessLevel: "ready",
    missingItems: [],
    suggestions: ["可继续写作"],
  },
};

export const mockSidebarData: SidebarData = {
  storySettings: ["废土纪元", "神秘频率", "第三区"],
  writingRules: ["主角不知道的信息不能写进内心独白", "不要一次性解释世界观", "每章结尾保留悬念感"],
  characters: ["林澈", "未知广播者", "避难所邻居"],
  locations: ["12层公寓避难所", "地下车库", "地下二层"],
  assets: ["旧收音机", "手电筒", "备用钥匙", "旧铜哨"],
  hooks: ["无线电异常信号", "地下车库异响", "避难所广播真假"],
  arcGoals: ["在旧城区灾变中生存下来", "确认广播源头但不揭开真相"],
};
